config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  get 'sanction/edit'
  resources :sanctions
  resources :countries
  resources :users
  resources :comments
  resources :favourites, :only => [:new, :create]
  resources :messages
  root :to => 'pages#home'
  get '/home' => 'pages#home'
  get '/about' => 'pages#about'
  delete 'countries/:id/edit' => 'countries#destroy'
  delete 'sanctions/:id/edit' => 'sanctions#destroy'
  get 'countries/:id/sanctions' => 'countries#sanctions'
  get 'sanctions/:id/favourites' => 'sanctions#favourites'
  post 'sanctions/:id/add_favourite' => 'sanctions#add_favourite'
  delete 'sanctions/:id/favourite' => 'sanctions#remove_favourite'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  post 'sanctions/:id/comment' => 'comments#create'
  delete 'users/:id/comments' => 'comments#remove_all_comments'
  delete '/messages' => 'messages#delete_all_messages'
  get 'users/:id/history' => 'comments#index'
  get 'users/:id/messenger' => 'messages#index', :as => :messages_path
  get 'users/:id/messages' => 'messages#message'

  # Our AJAX requests will be sent to this path:
  get '/api/unread' => 'dashboard#unread'
  get '/api/:id/messages' => 'dashboard#messages'

end

app/models/country.rb
class Country < ApplicationRecord
    has_many :dictators, dependent: :delete_all
    validates :name, :presence => true, :uniqueness => true
    has_many :sanctions, dependent: :delete_all
    validates_format_of :name, with: /[a-zA-Z]+/, message: "must contain at least one letter"
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :check_for_admin, only: [:edit]
  before_action :check_for_admin, only: [:new]
  before_action :check_for_admin, only: [:destroy]
  before_action :original_url, only: [:index]

  def index
    @countries = Country.includes(:sanctions).select { |c| c.sanctions.size > 0 }
    @countries = @countries.sort_by { |c| c.name }
    @all_countries = Country.all
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new country_params
    @country.name = titleize(@country.name)
    @country.save
    if @country.save
      redirect_to @country
    else
      render :new
    end
  end

  def edit
    @country = Country.find params[:id]
  end

  def update
    @country = Country.find params[:id]
    previous_name = @country.name
    @country.assign_attributes country_params
    @country.name = titleize(@country.name)
    begin
      if @country.flag.present? && !(@country.flag.include? 'cloudinary')
        req = Cloudinary::Uploader.upload(@country.flag)
        @country.flag = req['secure_url']
        @country.save
      end
    rescue StandardError
      @country.save
    end
    unless @country.name != previous_name && Country.find_by(name: @country.name).present?
      @country.save
      @country.sanctions.each do |sanction|
        sanction.nationality = @country.name
        sanction.save
      end
    end
    if @country.save
      redirect_to @country
    else
      render :edit
    end
  end

  def destroy
    country = Country.find params[:id]
    country.destroy
    redirect_to countries_path
  end

  def show
    unless params[:id].to_i > 0
      if Country.find_by(country_code: params[:id].upcase).nil?
        begin
          intended_country = ISO3166::Country.find_country_by_alpha2(params[:id]).unofficial_names[0]
        rescue StandardError
          intended_country = 'that country'
        end
        redirect_to countries_path,
                    alert: "Seems that none of our users have put any sanctions on #{intended_country} yet, why not start sanctioning people* from there now?"
        return

      elsif Country.find_by(country_code: params[:id].upcase).sanctions.size == 0

        intended_country = Country.find_by(country_code: params[:id].upcase).name

        redirect_to countries_path,
                    alert: "Seems that none of our users have put any sanctions on #{intended_country} yet, why not start sanctioning people* from there now?"
        return
      else
        params[:id] = Country.find_by(country_code: params[:id].upcase).id
      end
    end

    @country = Country.find params[:id]
    sanctions = Sanction.where(nationality: @country.name)
    if @country.sanctions.size != sanctions.size
      sanctions.each do |sanction|
        @country.sanctions << sanction
      end
    end

    if @country.official_name == '' || @country.official_name.nil?
      @country.official_name = (country_info @country.name)[:official_name]
      @country.save
    end
    if @country.native_name == '' || @country.native_name.nil?
      @country.native_name = (country_info @country.name)[:native_name]
      @country.save
    end
    if @country.flag == '' || @country.flag.nil?
      @country.flag = (country_info @country.name)[:flag]
      @country.save
    end

    if @country.country_code == '' || @country.country_code.nil?
      @country.country_code = (country_info @country.name)[:country_code]
      @country.save
    end

    return if @country.name == 'Unknown'

    if @country.description.nil?
      your_cse_id = 'e3218dc0a18944649' # www.google.com
      # your_cse_id = '57c3cb0530b3d4750' # www.google.com/imghp?hl=EN*
      wiki_search = "https://www.googleapis.com/customsearch/v1?key=#{your_api_key}&cx=#{your_cse_id}&q=#{@country.name.gsub(' ', '%20').gsub(
        ',', '%20'
      )}%20wikipedia"
      wiki_results = HTTParty.get wiki_search
      begin
        wiki_url = wiki_results['items'][0]['link']
        wiki = wiki_url[wiki_url.index('/wiki/') + 6..]
        dbpedia_url = "https://dbpedia.org/page/#{wiki}"
        dbpedia_doc = Nokogiri::HTML(URI.open(dbpedia_url))
        result = dbpedia_doc.search('span[property="dbo:abstract"][lang="en"]')
        @country_info = result.first.text
        @country.description = @country_info
        @country.save
      rescue StandardError
        @country_info = 'Not Available'
      end
    else
      @country_info = @country.description
    end
    @cia_factbook = {}
    filename = File.dirname(File.expand_path('..', __dir__)) + '/data/cia_factbook.csv'
    CSV.foreach(filename, headers: true, header_converters: :symbol, converters: :all) do |row|
      @cia_factbook[row.fields[0]] = Hash[row.headers[1..-1].zip(row.fields[1..-1])]
    end
    search = "#{@country.name} anthem"
    api_video_results = "https://www.googleapis.com/youtube/v3/search?key=#{your_api_key}&q=#{search}&type=video&part=snippet"
    video_results = HTTParty.get api_video_results
    @video = if !video_results.to_s.include?('error')
               'https://www.youtube.com/embed/' + video_results['items'][0]['id']['videoId']
             else
               video_results

             end
  end

  def sanctions
    params[:id] = Country.find_by(country_code: params[:id]).id unless params[:id].to_i > 0
    @country = Country.find params[:id]
    @sanctions = @country.sanctions.order(:name)
  end

  private

  def original_url
    @referer = request.path
  end

  def titleize(str)
    str.split(/ |_/).map(&:capitalize).join(' ')
  end

  def country_params
    params.require(:country).permit(:name, :official_name, :native_name, :country_code, :flag, :description)
  end

  def country_info(country_name)
    country_info = { official_name: nil, native_name: nil, country_code: nil, flag: nil }
    begin
      country_url = "https://restcountries.com/v3.1/name/#{country_name.gsub(' ', '%20')}?fullText=true"
      country_details = HTTParty.get country_url
      country_info[:official_name] = country_details[0]['name']['official']
      native_name_list = country_details[0]['name']['nativeName'].flatten
      native_name_list = native_name_list.drop(2) if native_name_list[0] == 'eng' && native_name_list.length > 2
      country_info[:native_name] = native_name_list[1]['official']
      country_info[:country_code] = country_details[0]['cca2']
      country_info[:flag] = country_details[0]['flags']['png']
    rescue StandardError
      begin
        country_details = ISO3166::Country.find_country_by_any_name(country_name)
        country_info[:official_name] = country_details.iso_long_name
        country_info[:country_code] = country_details.alpha2
      rescue StandardError
      end
    end

    country_info
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_for @country do |f| %>
    <%= f.label :name, "Name:", :required => true %>
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :official_name, "Official name:" %>
    <%= f.text_field :official_name %>
    <br>
    <br>
    <%= f.label :native_name, "Native official name:" %>
    <%= f.text_field :native_name %>
    <br>
    <br>
    <%= f.label :country_code, "Country code (CCA2):" %>
    <%= f.text_field :country_code %>
    <br>
    <br>
    <%= f.label :flag, "Flag:" %>
    <%= f.text_field :flag, placeholder: 'Type URL here..' %>
    <br>
    <br>
    <br>
    <%= f.submit %>

<% end %>

app/views/countries/edit.html.erb
<title><%= @country.name %> | Sancbook</title>

<h1>Update / Delete country</h1>
<% if @country.errors.any? %>
            <ol class="error">
                <% @country.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ol>
    <% end %>
<div class="form_container">
    <div>
        <%= render :partial => 'form' %>
        <br>
        <br>
        <%= button_to 'Delete Country', @country, :method => 'delete', :data => { :confirm => "Are you sure to delete this country? \n \n#{@country.sanctions.size} sanction(s) of this nationality will also be removed." } %>
    </div>
    <% unless @country["flag"].nil? || @country["flag"].empty? %>
        <figure class ='preview'>
            <img class="country_feature" src="<%= @country["flag"] %>" alt="<%= @country["name"] %>">  
        </figure>
    <% end%>
</div>

<script>

        figure = document.querySelector("figure");
        flag = document.querySelector("#country_flag");
        flag.addEventListener("input", function(){
        
        e = figure.lastElementChild
        if (flag.value != '') {
            img = document.createElement('img')
            img.src = flag.value
            figure.appendChild(img)
            figure.removeChild(e);
        } else {
            p = document.createElement('p')
            p.textContent = "Image from the URL will pop up here as you fill in the flag input box."
            figure.appendChild(p)
            figure.removeChild(e);


        }
    })
</script>

app/views/countries/index copy.html.erb
<title>Country index | Sancbook</title>

<h1>Countries index</h1>
<div class="country_number"><p>Currently there are <%= @countries.size %> countries where people have been sanctioned by our users.</p></div>

<div class="alert"><%= alert %></div>

<br><br>
<div class="country_index">
    <% if @current_user.present? %>
        <% if @current_user.admin? %>
             <% @all_countries.each do |country| %>
                <div class='thumb'>
                <% if country.country_code.present? %>
                    <a href="/countries/<%= country.country_code %>">
                <% else %>
                    <a href="/countries/<%= country.id %>">
                <% end %>
                    <img src="<%= country.flag %>" alt="<%= country["name"] %>">
                    <figcaption><%= country["name"] %></figcaption>
                    </a>
                </div>
            <% end %>
        <% else %>

            <% @countries.each do |country| %>
                <div class='thumb'>
                <% if country.country_code.present? %>
                    <a href="/countries/<%= country.country_code %>">
                <% else %>
                    <a href="/countries/<%= country.id %>">
                <% end %>
                    <img src="<%= country.flag %>" alt="<%= country["name"] %>">
                    <figcaption><%= country["name"] %></figcaption>
                    </a>
                
                </div>
            <% end%>
        <% end %>
    <% end %>
</div>
<br>

<p class='notice2' style="font-size:small;inline-height:50%;font-style:italic;">*who have commited serious violations or serious abuses of human rights</p>



<script>

    notice1 = document.querySelector('.notice1')
    notice2 = document.querySelector('.notice2')
    if (notice1.textContent.length == 6) {
        notice2.remove(notice2)
    }



</script>

app/views/countries/index.html.erb
<title>Country index | Sancbook</title>

<h1>Countries index</h1>
<div class="country_number"><p>Currently there are <%= @countries.size %> countries where people* have been sanctioned by our users.</p></div>

<div class="alert"><%= alert %></div>

<br><br>
<div class="country_index">
    <% if @current_user.present? %>
        <% if @current_user.admin? %>
             <% @all_countries.each do |country| %>
                <div class='thumb'>
                <% if country.country_code.present? %>
                    <a href="/countries/<%= country.country_code %>">
                <% else %>
                    <a href="/countries/<%= country.id %>">
                <% end %>
                    <img src="<%= country.flag %>" alt="<%= country["name"] %>">
                    <figcaption><%= country["name"] %></figcaption>
                    </a>
                </div>
            <% end %>
        <% end %>
    <% else %>
            <% @countries.each do |country| %>
                <div class='thumb'>
                <% if country.country_code.present? %>
                    <a href="/countries/<%= country.country_code %>">
                <% else %>
                    <a href="/countries/<%= country.id %>">
                <% end %>
                    <img src="<%= country.flag %>" alt="<%= country["name"] %>">
                    <figcaption><%= country["name"] %></figcaption>
                    </a>
                
                </div>
            <% end%>    
    <% end %>
</div>
<br>

<p class='notice2' style="font-size:small;inline-height:50%;font-style:italic;">*who have commited serious violations or serious abuses of human rights</p>



<script>

    notice1 = document.querySelector('.notice1')
    notice2 = document.querySelector('.notice2')
    if (notice1.textContent.length == 6) {
        notice2.remove(notice2)
    }



</script>

app/views/countries/new.html.erb
<title>New Country | Sancbook</title>

<h1>New country</h1>
<% if @country.errors.any? %>
            <ol class="error">
                <% @country.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ol>
    <% end %>

<div class="form_container">
    <%= render :partial => 'form' %>
<div class ='preview'><p>Image from the URL will pop up here as you fill in the flag input box.</p></div>
</div>

<script>

    preview = document.querySelector(".preview");
    flag = document.querySelector("#country_flag");
    flag.addEventListener("input", function(){
        
        e = preview.lastElementChild
        if (flag.value != '') {
            img = document.createElement('img')
            img.src = flag.value
            preview.appendChild(img)
            preview.removeChild(e);
        } else {
            p = document.createElement('p')
            p.textContent = "Image from the URL will pop up here as you fill in the flag input box."
            preview.appendChild(p)
            preview.removeChild(e);


        }
    })






</script>

app/views/countries/sanctions.html.erb
<title><%= @country.name %> | Sancbook</title>

<h1>Sanctions on <%= @country.name %></h1>
<p>Currently <%= @country.sanctions.size %> sanctions on this country.</p>
<br>
<div class="sanction_index">
    <% @sanctions.each do |sanction| %>
        <p>
            <a href="/sanctions/<%= sanction["id"] %>" data-turbolinks="false">
                <%= sanction["name"] %>
            </a>
        </p>
    <% end%>
</div>

app/views/countries/show.html.erb
<title><%= @country.name %> | Sancbook</title>

<div class="profile">
    <% unless @country["flag"].nil? || @country["flag"].empty? %>
    <figure>
        <img class="country_feature" src="<%= @country["flag"] %>" alt="<%= @country["name"] %>">
        <figcaption><%= @country.native_name %></figcaption>
    </figure>
    <% end%>

    <div class='details'>   
        <h2><%= @country.name %> <span><%= @country.country_code %></span></h2>
        <p><%= @country["official_name"] %></p>
        <p>Number of sanctions: <%= link_to "#{@country.sanctions.size}", "#{Country.find_by(id: params[:id]).country_code}/sanctions" %></p>
    </div>
</div>



<button type="button" class="collapsible">▼ National anthem - <%= @country["name"] %></button>
<div class="content">
    <% unless @video.nil?%>
        <% if @video.include? 'youtube.com/embed'%>
            <iframe width="420" height="315"src="<%= @video %>"></iframe>
        <% else%>
            <p><%= @video %></p>
        <% end%>
    <% end%>
</div>

<button type="button" class="collapsible">▼ Wikipedia - <%= @country["name"] %></button>
<div class="content">
    <p>
        <% if @country_info == "Not Available" %>
            Not available. <br> 
            Why don't you google it yourself? <br> 
            <a href="https://www.google.com/search?q=<%= @country["name"] %>">https://www.google.com/search?q=<%= @country["name"] %></a>
        <% else%>
        <%= @country_info %>
        <% end%></p>
</div>

    

<button type="button" class="collapsible">▼ CIA World Factbook 2018 - <%= @country["name"] %></button>
<div class="content">
    <% unless @cia_factbook.nil?%>
        <% if !@cia_factbook[@country["name"].gsub(' ', '-')].nil? %>
            <% @cia_factbook[@country["name"].gsub(' ', '-')].each do |key, value| %>
                <p>  
                <%= key.to_s.gsub('_', ' ') %>: <%= value %>
                </p>
            <% end %>
        <% else %>
            <p>Not available</p> 
        <% end %>
    <% end %>
</div>

<% if @current_user.present? %>
    <% if @current_user.admin? %>
        <div class="control">
            <%= link_to 'Update / Delete country', edit_country_path(@country) %>
        </div>
    <% end %>
<% end %>

<script>
    colls = document.querySelectorAll(".collapsible");
    colls.forEach(target =>
        target.addEventListener("click", function() {
            this.classList.toggle("active");
            let content = this.nextElementSibling;
            if (content.style.display === "block") {
            content.style.display = "none";
            } else {
            content.style.display = "block";
            }

            if (this.classList.contains("active")) {
                this.textContent = this.textContent.replace('▼', '▲')
            }
            else {
                this.textContent = this.textContent.replace('▲', '▼')
            }
        }))
    
    container = document.querySelector(".container")
    h2 = document.querySelector("h2")
    contents = document.querySelectorAll(".content");
    if (h2.textContent == 'Unknown') {
        colls.forEach(target =>
            container.removeChild(target)
        )
        contents.forEach(target =>
            container.removeChild(target)
        )
    }

    </script>