config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  get 'sanction/edit'
  resources :sanctions
  resources :countries
  resources :users
  resources :comments
  resources :favourites, :only => [:new, :create]
  resources :messages
  root :to => 'pages#home'
  get '/home' => 'pages#home'
  get '/about' => 'pages#about'
  delete 'countries/:id/edit' => 'countries#destroy'
  delete 'sanctions/:id/edit' => 'sanctions#destroy'
  get 'countries/:id/sanctions' => 'countries#sanctions'
  get 'sanctions/:id/favourites' => 'sanctions#favourites'
  post 'sanctions/:id/add_favourite' => 'sanctions#add_favourite'
  delete 'sanctions/:id/favourite' => 'sanctions#remove_favourite'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  post 'sanctions/:id/comment' => 'comments#create'
  delete 'users/:id/comments' => 'comments#remove_all_comments'
  delete '/messages' => 'messages#delete_all_messages'
  get 'users/:id/history' => 'comments#index'
  get 'users/:id/messenger' => 'messages#index', :as => :messages_path
  get 'users/:id/messages' => 'messages#message'

  # Our AJAX requests will be sent to this path:
  get '/api/unread' => 'dashboard#unread'
  get '/api/:id/messages' => 'dashboard#messages'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :sanction
    belongs_to :user
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :dictators, dependent: :delete_all
    validates :name, :presence => true, :uniqueness => true
    has_many :sanctions, dependent: :delete_all
    validates_format_of :name, with: /[a-zA-Z]+/, message: "must contain at least one letter"
end

app/models/country_name.rb
class Country_name < ApplicationRecord
    belongs_to :country
end

app/models/dictator.rb
class Dictator < ApplicationRecord
    belongs_to :country, :optional => true
    has_and_belongs_to_many :favourites
    validates :name, :presence => true, :uniqueness => true
    belongs_to :user, :optional => true
    
end

app/models/favourite.rb
class Favourite < ApplicationRecord
    validates :sanction_id, presence: true, uniqueness: { scope: :user_id }
    validates :user_id, presence: true, uniqueness: { scope: :sanction_id }
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :sender, class_name: "User", foreign_key: 'sender_id'
    belongs_to :receiver, class_name: "User", foreign_key: 'receiver_id'

    validates_with DifferentValidator
end

app/models/sanction.rb
class Sanction < ApplicationRecord
    validates :name, :uniqueness => true, :presence => true, uniqueness: { case_sensitive: false }
    validates_format_of :name, with: /[a-zA-Z]+/, message: "must contain at least one letter"

    belongs_to :country, :optional => true
    has_many :favourites, dependent: :delete_all
    belongs_to :user, :optional => true
    has_many :comments, dependent: :delete_all

    
    
  






end

app/models/user.rb
class User < ApplicationRecord
    has_many :dictators, dependent: :delete_all
    has_many :favourites, dependent: :delete_all
    has_many :sanctions, dependent: :delete_all
    has_many :comments, dependent: :delete_all
    has_many :sent_messages, dependent: :delete_all, class_name: "Message", foreign_key: "sender_id"
    has_many :received_messages, dependent: :delete_all, class_name: "Message", foreign_key: "receiver_id"
    has_many :unread_messages, -> { where(read: false) }, class_name: 'Message', foreign_key: 'receiver_id', dependent: :delete_all

    validates_confirmation_of :password
    has_secure_password
    validates :email, :uniqueness => true, :presence => true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z][a-zA-Z0-9\.]*@[a-zA-Z0-9]+\.[a-zA-Z0-9]+\z/, message: "must be in the format of 'user@example.com'" }
    validates :username, :uniqueness => true, :presence => true, uniqueness: { case_sensitive: false }
    validates :username, length: { in: 3..15 }
    validates :username, format: { with: /\A[a-zA-Z0-9]+\z/, message: "can only contain letters and numbers" }
    validates_format_of :username, with: /[a-zA-Z]+/, message: "must contain at least one letter"
    validate :pasword_must_not_be_blank
    


    def pasword_must_not_be_blank
      if password.blank?
        errors.add(:password, "must not be blank")
      end
    end

    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    countries = Country.order(:name)
    country_codes = []
    country_sanctions_lengths = []
    countries.each do |country|
      if country.country_code.present?
        country_codes.push(country.country_code)
      else
        country_codes.push(country.name)
      end
      country_sanctions_lengths.push country.sanctions.length
    end
    gon.sanctionedCountryCodes = country_codes
    gon.countrySanctionsLengths = country_sanctions_lengths

  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/country_name_helper.rb
module CountryNameHelper
end

app/helpers/dictator_helper.rb
module DictatorHelper
end

app/helpers/dictators_helper.rb
module DictatorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sanction_helper.rb
module SanctionHelper
end

app/helpers/sanctions_helper.rb
module SanctionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <div class="container">
      <header>
        <div class="logo">
            <a href="/" data-turbolinks="false" style="font-weight:bold;text-decoration:none">Sancbook</a></div>
            <div class="link">

          <nav class='left'>
            <%= link_to "All countries", countries_path %>
            <% if @current_user.present? %>
              <% if @current_user.admin? %>
                <%= link_to "New country", new_country_path %>
              <% end %>
            <% end %>
            <%= link_to "All sanctions", sanctions_path %>
            <% if @current_user.present? %>
              <%= link_to "New sanction", new_sanction_path %>
            <% end %>
            <%= link_to "About Us", about_path %>
        </nav>
        <nav class='right'>
        <% if @current_user.present? %>
              <div>
            <%= link_to "Logout", login_path, :method => 'delete' %>&nbsp(<%= link_to "#{@current_user.username}", "/users/#{User.find_by(id: @current_user.id).username}" %>)</div>
            <a href=<%= "/users/#{User.find_by(id: @current_user.id).username}/messenger" %>><span id='unread'>Messenger</span></a>


           

        <% else %>
            <%= link_to "Login / Signup", login_path %>
        <% end %>
        </nav>
            </div>

      </header>
    <br>
      <section class="view">
        <%= yield %>
      </section>
    </div>
  </body>

  <footer> <div><%= link_to "About us", about_path %>© 2023 Sancbook</div></footer>
  
</html>

app/views/pages/about.html.erb
<title>About us | Sancbook</title>

<div class="about">
<h1 class="aboutGreeting">Hi, we are Sancbook</h1>

<div class="aboutText">
    <p><span class= 'aboutBrand'>Sancbook</span>, probably the largest online social media and social networking service about sanctions in the world. We're commited to connecting people through sanctioning. Our goal is to attract people who have a sense of justice, discussing measures to stop civil and political rights violations, but most importantly, making like-minded friends across the globe!</p>
    <p>The main source of the sanctions discussed on Sancbook originates from the <a href="https://ofac.treasury.gov/specially-designated-nationals-list-data-formats-data-schemas" target="_blank">U.S. Department of the Treasury</a>, and we strive to keep our community informed and engaged in conversations that matter. Join us in building a community that stands against civil and political rights violations, and let's make a positive impact together!</p>
    <p>Explore the world of sanctions and justice at <a href="/">Sancbook</a>.</p>
</div>
</div>

app/views/pages/home.html.erb
<title>Sancbook</title>

<h1> Welcome to Sancbook,
    <% if @current_user.present? %><%= @current_user.username %><% else %>Visitor<% end %>! <h1>

<h3 class='mapHeader'>Below countries shown in red are countries where some of the individuals have been sanctioned by some countries in the world or have been requested to get sanctioned from our users . You can also add new sanctions and hopefully some government* in the world would notice your request. Click on the map NOW! Check out whom have been^ sanctioned, show your support or disapproval, and make friends around the world!</h3>
<div class='postscript'>
<p>*Not exclusive to Western democratic countries. Russia and North Korea, for instance, may also listen to your request</p>
<p>^or to be</p>
</div>
<div>
<div id="map"></div>
</div>
<br>
<h4 class='mapFooter'>If your favourite country is not in red colour yet, please create a new sanction on that country and let us know why they deserve to be punished!</h4>

<turbo-frame>
    <%= javascript_include_tag "mapdata" %>
</turbo-frame>

<script>

mapHeader = document.querySelector(".mapHeader")
pScreen = document.querySelector(".pScreen")
postscript = document.querySelector(".postscript")

isMobile = Math.min(window.screen.width, window.screen.height) < 768 || navigator.userAgent.indexOf("Mobi") > -1;

if(isMobile) {
    mapHeader.textContent = "Click on the map NOW! Check out whom have been* sanctioned, show your support*, and make friends around the world!"
   mapHeader.style.marginBottom = "30px";
   pScreen.style.display = "none"
}


</script>